# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Web Dev To Be
tagline:             'Andrzej Brandt'
description:         'Hello! I\'m Andrzej Brandt and this blog documents a way of becoming Ruby Developer'
url:                 http://anbrandt.github.io/blog
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Andrzej Brandt
  url:               https://github.com/anbrandt
  email:             andrzej.brandt@gmail.com

# Custom vars
version:             1.0.0
